config/routes.rb
Rails.application.routes.draw do
  resources :case_files, :defaults => { :format => :json }

    match '/case_files', :controller => 'case_files', :action => 'options', via: [:options], :constraints => {:method => 'OPTIONS'}
    match '/case_files/:id', :controller => 'case_files', :action => 'options', via: [:options], :constraints => {:method => 'OPTIONS'}

end

app/models/blob.rb
class Blob

  attr_reader :data

  def initialize(hash={})
    @data = hash
  end
  
  def update(new_hash)
    new_hash.keys.each do |key|
      if @data.key?(key)
        update_data(new_hash, key)
      else
        @data[key] = new_hash[key]
      end
    end
  end

  def update_data(new_hash, key)
    if @data[key].is_a?(Hash)
      blob = Blob.new(@data[key])
      blob.update(new_hash[key])
      @data[key] = blob.data
    else
      @data[key] = new_hash[key]
    end
  end

end

app/models/case_file.rb
# == Schema Information
#
# Table name: case_files
#
#  id         :integer          not null, primary key
#  urn        :string(255)
#  blob       :text
#  created_at :datetime
#  updated_at :datetime
#  urn_id     :integer
#

class CaseFile < ActiveRecord::Base

  belongs_to :urn

  FORCE_CODE = '06JJ'

  serialize :blob, Hash
  scope :by_id, -> { all.order(:id) }
  after_initialize :generate_urn_and_empty_blob


  def update_blob(blob_updates_as_json)
    blob_updates = ActiveSupport::JSON.decode blob_updates_as_json
    blob_obj = Blob.new(self.blob)
    blob_obj.update(blob_updates)
    self.blob = blob_obj.data
    self.save!
  end

  def urn_code
    self.urn.urn_code
  end

  
  private

  def generate_urn_and_empty_blob
    if self.urn.nil?
      self.urn = Urn.new(force_code: FORCE_CODE)
      self.save
    end
    self.blob = Blob.new.data if self.blob.nil?
  end


  def recursive_merge( merge_from, merge_to )
    merged_hash = merge_to.clone
    first_key = merge_from.keys[0]
    if merge_to.has_key?(first_key)
        merged_hash[first_key] = recursive_merge( merge_from[first_key], merge_to[first_key] )
    else
        merged_hash[first_key] = merge_from[first_key]
    end
    merged_hash
  end





end

app/models/urn.rb
# == Schema Information
#
# Table name: urns
#
#  id         :integer          not null, primary key
#  force_code :string(255)
#  year_code  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Urn < ActiveRecord::Base

  validates :force_code, :year_code, presence: true
  validates :year_code, numericality: true

  after_initialize :populate_year_code

  def urn_code
    save! if new_record?
    sprintf("%s%05d%s", self.force_code, self.id, self.year_code)
  end



  private

  def populate_year_code
    self.year_code = Date.today.strftime('%y')
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	ALLOWED_HOSTS = [
		'http://localhost:3000',
		'http://localhost:9000',
		'https://dcf-frontend.herokuapp.com'
	]


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  # before_filter :add_headers


  private


  # Adds the Access-Control-Allow-Origin header to allow access from anywhere.
  # If a list of allowed origins is required, then the client must send an Origin header,
  # and the server compares it with a whitelist, and returns a single uri as the allowed origin
  # if it is in that whitelist.
  #
 #  def add_headers




    
 #  	response.headers["Access-Control-Allow-Origin"] = '*'
	# end



end

app/controllers/case_files_controller.rb
class CaseFilesController < ApplicationController
  respond_to :json
  before_action :set_case_file, only: [:show, :edit, :update]


  def options
      head :ok
  end


  # GET /case_files
  # GET /case_files.json
  def index
    require 'pp'
    @case_files = CaseFile.by_id
    respond_to do |format|
      format.json
    end
  end

  # GET /case_files/1
  # GET /case_files/1.json
  def show
    respond_to do |format|
      format.json
    end
  end

  # GET /case_files/new
  def new
    @case_file = CaseFile.new
    @case_file.save!
    respond_to do |format|
      format.json 
    end
  end

  # GET /case_files/1/edit
  # def edit
  # end

  # POST /case_files
  # POST /case_files.json
  # def create
  #   @case_file = CaseFile.new(case_file_params)

  #   respond_to do |format|
  #     if @case_file.save
  #       format.html { redirect_to @case_file, notice: 'Case file was successfully created.' }
  #       format.json { render :show, status: :created, location: @case_file }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @case_file.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /case_files/1
  # PATCH/PUT /case_files/1.json
  def update
    @case_file.update_blob(params['case_file'])
    respond_to do |format|
      format.json
    end
  end

  # DELETE /case_files/1
  # DELETE /case_files/1.json
  def destroy
    @case_file = CaseFile.where(id: params[:id]).first
    if @case_file.nil?
      render json: "Record not found", status: 404
    else
      @case_file.destroy
      render json: "Record deleted"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case_file
      @case_file = CaseFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_file_params
      params.require(:case_file).permit(:urn, :blob)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case_files_helper.rb
module CaseFilesHelper
end

app/views/case_files/_form.html.erb
<%= form_for(@case_file) do |f| %>
  <% if @case_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case_file.errors.count, "error") %> prohibited this case_file from being saved:</h2>

      <ul>
      <% @case_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :urn %><br>
    <%= f.text_field :urn %>
  </div>
  <div class="field">
    <%= f.label :blob %><br>
    <%= f.text_area :blob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/case_files/edit.html.erb
<h1>Editing case_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @case_file %> |
<%= link_to 'Back', case_files_path %>

app/views/case_files/index.html.erb
<h1>Listing case_files</h1>

<table>
  <thead>
    <tr>
      <th>Urn</th>
      <th>Blob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @case_files.each do |case_file| %>
      <tr>
        <td><%= case_file.urn %></td>
        <td><%= case_file.blob %></td>
        <td><%= link_to 'Show', case_file %></td>
        <td><%= link_to 'Edit', edit_case_file_path(case_file) %></td>
        <td><%= link_to 'Destroy', case_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Case file', new_case_file_path %>

app/views/case_files/new.html.erb
<h1>New case_file</h1>

<%= render 'form' %>

<%= link_to 'Back', case_files_path %>

app/views/case_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Urn:</strong>
  <%= @case_file.urn %>
</p>

<p>
  <strong>Blob:</strong>
  <%= @case_file.blob %>
</p>

<%= link_to 'Edit', edit_case_file_path(@case_file) %> |
<%= link_to 'Back', case_files_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DcfBackend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>